name: 'GRESB Test'
description: 'Run GRESB integration tests'
inputs:
  application-command:
    description: 'The command name for executing the application.'
    required: true
    default: 'gresb-test'
  application-version:
    description: 'The version of gresb-test to use.'
    required: true
  cmd-args:
    description: 'The arguments passed to gresb-test.'
    required: true
    default: '-V'
  installation-github-pat:
    description: 'The GitHub token used for downloading the installation script.'
    required: true
  installation-aws-access-key-id:
    description: 'The AWS access key id used to install gresb-test. Needs access to the gresb-application-versions S3 bucket.'
    required: false
  installation-aws-secret-access-key:
    description: 'The AWS secret access key used to install gresb-test. Needs access to the gresb-application-versions S3 bucket.'
    required: false
  installation-aws-role-arn:
    description: 'The AWS IAM role used to install gresb-test. Needs access to the gresb-application-versions S3 bucket.'
    required: false
  installation-aws-role-session-name:
    description: 'The session name used when getting the token.'
    required: false
    default: "github-action-gresb-test"
  test-aws-access-key-id:
    description: 'The AWS access key id used to run tests that require interaction with AWS APIs.'
    required: false
  test-aws-secret-access-key:
    description: 'The AWS secret access key used to run tests that require interaction with AWS APIs.'
    required: false
  test-aws-role-arn:
    description: 'The AWS IAM role arn used to run tests that require interaction with AWS APIs.'
    required: false
  test-aws-role-session-name:
    description: 'The session name used when interacting with AWS APIs.'
    required: false
    default: "github-action-gresb-test"
  test-mailtrap-token:
    description: 'The Mailtrap token used to run tests that require interaction with Mailtrap APIs.'
    required: false
  test-slack-token:
    description: 'The Slack token used to run tests that require interaction with Slack APIs.'
    required: false
  test-gresb-portal-user-password:
    description: 'The password for the default test user in the portal.'
    required: false
  test-cluster-api-key:
    description: 'The Kafka cluster api key.'
    required: false
  test-cluster-api-secret:
    description: 'The Kafka cluster api secret.'
    required: false
  test-datadog-api-key:
    description: 'The Datadog API key.'
    required: false
  test-datadog-app-key:
    description: 'The Datadog APP key.'
    required: false
  test-datadog-site:
    description: 'The Datadog site.'
    required: false
    default: 'datadoghq.eu'
  test-github-token:
    description: 'The GitHub token used by the tests.'
    required: false
  test-onepassword-svc-vault-token:
    description: 'The OnePassword service vault token.'
    required: true
outputs:
  log:
    description: 'The test log.'
    value: ${{ steps.run-tests.outputs.log }}
runs:
  using: "composite"
  steps:
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        java-package: jre
    - name: Install system packages
      uses: awalsh128/cache-apt-pkgs-action@v1.3.1
      with:
        packages: colorized-logs
        version: 1.0
    - name: Cache application
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/GRESB/${{ inputs.application-command }}
          /usr/local/bin/${{ inputs.application-command }}
        key: ${{ runner.os }}-${{ inputs.application-command }}-${{ inputs.application-version }}
        restore-keys: ${{ runner.os }}-${{ inputs.application-command }}
    - name: AWS credentials for installation
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region:  eu-central-1
        role-to-assume: ${{ inputs.installation-aws-role-arn }}
        role-session-name: ${{ inputs.installation-aws-role-session-name }}
        aws-access-key-id: ${{ inputs.installation-aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.installation-aws-secret-access-key }}
    - name: Install application
      shell: bash
      run: |
        if ! (which ${cmd}) || ! (${cmd} -V | grep "${gresb_test_version}"); then
          echo "DEBUG :: which ${cmd} = $( which ${cmd} )"
          echo "DEBUG :: ${cmd} -V    = $( ${cmd} -V )"

          install_script=/tmp/install.sh
          curl -H "Authorization: token ${pat}" -o "${install_script}" "https://raw.githubusercontent.com/GRESB/test-automation/${gresb_test_version}/test-runner/install.sh"
          chmod +x "${install_script}"
          echo "==> Installing ${cmd} ${gresb_test_version}"
          "${install_script}" "${gresb_test_version}"
          rm -f "${install_script}"
        else
          echo "==> ${cmd} ${gresb_test_version} already installed"
        fi
      env:
        cmd: ${{ inputs.application-command }}
        gresb_test_version: ${{ inputs.application-version }}
        pat: ${{ inputs.installation-github-pat }}
    - name: AWS credentials for tests
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region:  eu-central-1
        role-to-assume: ${{ inputs.test-aws-role-arn }}
        role-session-name: ${{ inputs.test-aws-role-session-name }}
        aws-access-key-id: ${{ inputs.test-aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.test-aws-secret-access-key }}
    - name: Run integration tests
      id: run-tests
      shell: bash
      run: |
        cmd="${cmd} ${cmd_args}"
        echo "DEBUG :: executing = ${cmd}"
        output_file=".output.txt"
        set +e
        ${cmd} 2>&1 | ansi2txt | tee "${output_file}"
        status=$?
        {
          echo "status=${status}"
          END_OF_VALUE=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "log<<${END_OF_VALUE}";
          cat "${output_file}";
          echo "${END_OF_VALUE}"
        } >> "${GITHUB_OUTPUT}"
      env:
        cmd: ${{ inputs.application-command }}
        cmd_args: ${{ inputs.cmd-args }}
        MAILTRAP_TOKEN: ${{ inputs.test-mailtrap-token }}
        SLACK_TOKEN: ${{ inputs.test-slack-token }}
        GRESB_RUN_HEADLESS: "true"
        GRESB_PORTAL_PASSWORD: ${{ inputs.test-gresb-portal-user-password }}
        CLUSTER_API_KEY: ${{ inputs.test-cluster-api-key }}
        CLUSTER_API_SECRET: ${{ inputs.test-cluster-api-secret }}
        DD_API_KEY: ${{ inputs.test-datadog-api-key }}
        DD_APP_KEY: ${{ inputs.test-datadog-app-key }}
        DD_SITE: ${{ inputs.test-datadog-site }}
        GITHUB_TOKEN: ${{ inputs.test-github-token }}
        OP_SVC_VAULT_TOKEN: ${{ secrets.test-onepassword-svc-vault-token }}
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-artifacts
        path: |
          screenshots/
          traces/
          TEST-junit-*.xml
        retention-days: 5
    - name: Set status
      shell: bash
      if: always()
      env:
        status: ${{ steps.run-tests.outputs.status }}
      run: exit ${status}
